<?php

namespace BayonetsAndTomahawks;

const OPTION_SCENARIO = 100;
const OPTION_SCENARIO_1 = 1;
const OPTION_SCENARIO_2 = 2;
const OPTION_SCENARIO_3 = 3;
const OPTION_SCENARIO_4 = 4;

const OPTION_FACTIONS = 101;
const OPTION_FACTIONS_RANDOM = 0;
const OPTION_FACTIONS_TABLE_ADMIN_BRITISH = 1;
const OPTION_FACTIONS_TABLE_ADMIN_FRENCH = 2;